import 'package:flutter/material.dart';
import 'package:sdui/sdui.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Expanded(
            child: SDUIFrame(
              formJson: {
                "name": "Euro Sepa Instant Form",
                "key": "sepa_instant_form",
                "title": null,
                "description": null,
                "version": 1,
                "meta": {
                  "ui": {"layout": "wizard", "progress": true},
                  "i18n": {"defaultLocale": "en", "translations": []},
                },
                "properties": {
                  "dateFormat": "YYYY-MM-DD",
                  "timeFormat": "HH:mm",
                  "datetimeFormat": "YYYY-MM-DDTHH:mm:ssZ",
                  "numberFormat": {"decimal": ".", "thousand": ","},
                },
                "form": {
                  "pages": [
                    {
                      "key": "euro_iban",
                      "label": "Page",
                      "description": null,
                      "order": 1,
                      "sections": [
                        {
                          "key": "section_1",
                          "label": null,
                          "description": null,
                          "order": 1,
                          "fields": [
                            {
                              "key": "full_name",
                              "label": "Full name of the account holder",
                              "placeholder": "Enter full name",
                              "help_text": null,
                              "default": null,
                              "type": "short-text",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "min": null,
                                "max": null,
                                "min_length": null,
                                "max_length": null,
                                "accept": [],
                                "max_size": null,
                                "step": null,
                              },
                            },
                            {
                              "key": "iban",
                              "label": "IBAN",
                              "placeholder": "Enter IBAN",
                              "help_text":
                                  "IBANs are international bank account numbers used for transfers abroad. They always begin with a two-letter country code, like DE for Germany.",
                              "default": null,
                              "type": "short-text",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "min": null,
                                "max": null,
                                "min_length": null,
                                "max_length": null,
                                "accept": [],
                                "max_size": null,
                                "step": null,
                              },
                            },
                            {
                              "key": "email",
                              "label": "Their email (optional)",
                              "placeholder": "Enter Email",
                              "help_text": null,
                              "default": null,
                              "type": "email",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": false,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "allowed_domains": [],
                                "disallowed_domains": [],
                                "max_length": null,
                              },
                            },
                          ],
                        },
                        {
                          "key": "section_2",
                          "label": "section 2 label",
                          "description": "This is a section description.",
                          "order": 2,
                          "fields": [
                            {
                              "key": "terms_and_conditions",
                              "label": "Accept our terms and condition",
                              "placeholder": null,
                              "help_text":
                                  "By continuing, you accept our [terms and conditions](https://basewallet.co/privacy).",
                              "default": null,
                              "type": "boolean",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {},
                            },
                            {
                              "key": "email_with_domains",
                              "label": "Enter a valid email",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "email",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": false,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "allowed_domains": ["apexnetwork.co"],
                                "disallowed_domains": ["gmail.com"],
                                "max_length": 60,
                              },
                            },
                            {
                              "key": "options",
                              "label": "Options Single Select Field",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "options",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": false,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [
                                {
                                  "rule": "in",
                                  "message":
                                      "The selected country isn't supported",
                                  "params": [],
                                },
                              ],
                              "constraints": {},
                              "option_properties": {
                                "type": "select",
                                "data": [
                                  {"key": "one", "value": "One"},
                                  {"key": "two", "value": "Two"},
                                  {"key": "three", "value": "Three"},
                                ],
                                "max_select": null,
                              },
                            },
                            {
                              "key": "options_multi",
                              "label": "Multi Select",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "options",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": false,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {},
                              "option_properties": {
                                "type": "multi-select",
                                "data": [
                                  {"key": "one", "value": "Two"},
                                  {"key": "two", "value": "Two"},
                                  {"key": "three", "value": "Three"},
                                ],
                                "max_select": null,
                              },
                            },
                            {
                              "key": "radio_1",
                              "label": "Radio Label",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "options",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": false,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {},
                              "option_properties": {
                                "type": "radio",
                                "data": [
                                  {"key": "no", "value": "No"},
                                  {"key": "yes", "value": "Yes"},
                                ],
                                "max_select": null,
                              },
                            },
                            {
                              "key": "text_field",
                              "label": "Text Field Label",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "text",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 2,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "min": null,
                                "max": null,
                                "min_length": null,
                                "max_length": null,
                                "accept": [],
                                "max_size": null,
                                "step": null,
                              },
                            },
                            {
                              "key": "medium_text_field",
                              "label": "Medium Text Field",
                              "placeholder": "Medium text field placeholder",
                              "help_text": null,
                              "default": null,
                              "type": "medium-text",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 4,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "min": null,
                                "max": null,
                                "min_length": null,
                                "max_length": null,
                                "accept": [],
                                "max_size": null,
                                "step": null,
                              },
                            },
                            {
                              "key": "long_text_field",
                              "label": "Long Field Text Label",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "long-text",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 8,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "min": null,
                                "max": null,
                                "min_length": null,
                                "max_length": null,
                                "accept": [],
                                "max_size": null,
                                "step": null,
                              },
                            },
                            {
                              "key": "number_field",
                              "label": "Number Field Label",
                              "placeholder": null,
                              "help_text":
                                  "Step is 2, meaning step is an increase of two if arrow keys are available or shown",
                              "default": null,
                              "type": "number",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "min": 2,
                                "max": 1000,
                                "min_length": null,
                                "max_length": null,
                                "accept": [],
                                "max_size": null,
                                "step": 2,
                              },
                            },
                            {
                              "key": "date_field",
                              "label": "Date Field Label",
                              "placeholder": null,
                              "help_text":
                                  "this is using a before and after validation",
                              "default": null,
                              "type": "date",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [
                                {
                                  "rule": "before",
                                  "message": null,
                                  "params": [],
                                },
                                {
                                  "rule": "after",
                                  "message": null,
                                  "params": [],
                                },
                              ],
                              "constraints": {},
                            },
                            {
                              "key": "datetime_field",
                              "label": "datetime label",
                              "placeholder": null,
                              "help_text":
                                  "should be a date and time selection",
                              "default": null,
                              "type": "datetime",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": false,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {},
                            },
                            {
                              "key": "file_field",
                              "label": "File upload label",
                              "placeholder": null,
                              "help_text": "mime type empty, so any file",
                              "default": null,
                              "type": "file",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": false,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "accept": [
                                  "application/pdf",
                                  "application/msword",
                                  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                                  "application/vnd.ms-excel",
                                  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                  "application/vnd.ms-powerpoint",
                                  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                                ],
                                "min": 1,
                                "max": null,
                                "allow_multiple": false,
                                "max_file_size": null,
                                "max_total_size": null,
                              },
                            },
                            {
                              "key": "image_field",
                              "label": "Image upload label",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "image",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "accept": [
                                  "image/jpeg",
                                  "image/png",
                                  "image/webp",
                                  "image/svg+xml",
                                  "image/avif",
                                  "image/heic",
                                  "image/heif",
                                ],
                                "min": 1,
                                "max": null,
                                "allow_multiple": false,
                                "max_file_size": null,
                                "max_total_size": null,
                              },
                            },
                            {
                              "key": "image_multiple",
                              "label": "Image with multiple",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "image",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": false,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "accept": [
                                  "image/jpeg",
                                  "image/png",
                                  "image/webp",
                                  "image/svg+xml",
                                  "image/avif",
                                  "image/heic",
                                  "image/heif",
                                ],
                                "min": 1,
                                "max": null,
                                "allow_multiple": true,
                                "max_file_size": 1000000,
                                "max_total_size": null,
                              },
                            },
                            {
                              "key": "video_field",
                              "label": "Video Upload field",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "video",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": false,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "accept": [
                                  "video/mp4",
                                  "video/quicktime",
                                  "video/x-msvideo",
                                  "video/x-ms-wmv",
                                ],
                                "min": 1,
                                "max": null,
                                "allow_multiple": false,
                                "max_file_size": null,
                                "max_total_size": null,
                              },
                            },
                            {
                              "key": "video_field",
                              "label":
                                  "Video Upload field with 1000000 max file size",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "video",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": false,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "accept": [
                                  "video/mp4",
                                  "video/quicktime",
                                  "video/x-msvideo",
                                  "video/x-ms-wmv",
                                ],
                                "min": 1,
                                "max": null,
                                "allow_multiple": false,
                                "max_file_size": 1000000,
                                "max_total_size": null,
                              },
                            },
                            {
                              "key": "document_field",
                              "label": "Document field",
                              "placeholder": null,
                              "help_text": "has mime types",
                              "default": null,
                              "type": "document",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": false,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "accept": [
                                  "application/pdf",
                                  "application/msword",
                                  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                                  "application/vnd.ms-excel",
                                  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                  "application/vnd.ms-powerpoint",
                                  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                                ],
                                "min": 1,
                                "max": null,
                                "allow_multiple": false,
                                "max_file_size": null,
                                "max_total_size": null,
                              },
                            },
                            {
                              "key": "tag_field",
                              "label": "Tag Field",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "tag",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": false,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {},
                            },
                            {
                              "key": "phone",
                              "label": "Phone Number",
                              "placeholder": "Enter a valid phone",
                              "help_text": null,
                              "default": null,
                              "type": "phone",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "code_type": "alpha_2",
                                "allow_countries": [],
                                "exclude_countries": [],
                                "format": "e164",
                              },
                            },
                            {
                              "key": "url",
                              "label": "Instagram URL",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "url",
                              "visible_if": {"all": [], "any": [], "not": null},
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {},
                            },
                            {
                              "key": "country",
                              "label": "All Country",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "country",
                              "visible_if": {
                                "all": [],
                                "any": [],
                                "not": {"key": "value"},
                              },
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "code_type": "alpha_2",
                                "allow_countries": [],
                                "exclude_countries": [],
                              },
                            },
                            {
                              "key": "country",
                              "label": "Country With NG Allowed",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "country",
                              "visible_if": {
                                "all": [],
                                "any": [],
                                "not": {"key": "value"},
                              },
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "code_type": "alpha_2",
                                "allow_countries": ["NG"],
                                "exclude_countries": [],
                              },
                            },
                            {
                              "key": "country",
                              "label": "Country With NG and US Disallowed",
                              "placeholder": null,
                              "help_text": null,
                              "default": null,
                              "type": "country",
                              "visible_if": {
                                "all": [],
                                "any": [],
                                "not": {"key": "value"},
                              },
                              "readonly": false,
                              "required": true,
                              "ui": {
                                "icon": null,
                                "prefix": null,
                                "suffix": null,
                                "mask": null,
                                "multiline_rows": 1,
                                "max_length": 255,
                              },
                              "validations": [],
                              "constraints": {
                                "code_type": "alpha_2",
                                "allow_countries": [],
                                "exclude_countries": ["NG", "US"],
                              },
                            },
                          ],
                        },
                      ],
                    },
                  ],
                  "pages_count": 1,
                },
              },
              onSubmit: (formData) {
                print('Form submitted with data: $formData');
                // Handle form submission
              },
              onFieldChanged: (key, value) {
                print('Field $key changed to: $value');
                // Handle field changes
              },
            ),
          ),
        ],
      ),
    );
  }
}

class SizedBoxWidget extends SDUIBaseWidget {
  const SizedBoxWidget({
    super.key,
    required super.field,
    required super.formManager,
    super.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    return const SizedBox();
  }

  @override
  String? validateField(value) {
    return null;
  }
}
