import 'package:example/custom_fields/custom_field_kit.dart';
import 'package:example/form_view.dart';
import 'package:flutter/material.dart';

void main() {
  ExampleCustomFieldKit.register();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
  }

  navigateToFormView({
    Map<String, dynamic>? formJson,
    String? formId,
    String? formUrl,
  }) async {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) {
          return FormView(formJson: formJson, formId: formId, formUrl: formUrl);
        },
      ),
    );
  }

  usaWireTransferForm() {
    navigateToFormView(
      formJson: {
        "key": "nigeria_bank_transfer_form",
        "form": {
          "pages": [
            {
              "id": "019cb8c8-a823-7079-b579-4d29cf0317fb",
              "key": "page_1",
              "label": "",
              "order": 1,
              "hidden": false,
              "sections": [
                {
                  "id": "019cb8c8-a823-7079-b579-5315849f2868",
                  "key": "section_1",
                  "label": null,
                  "order": 1,
                  "fields": [
                    {
                      "id": "019cb8c9-2b94-77c9-bf73-7536d7dd1c2c",
                      "ui": {
                        "icon": null,
                        "mask": null,
                        "prefix": null,
                        "suffix": null,
                        "input_mode": null,
                        "max_length": null,
                        "autocomplete": null,
                        "multiline_rows": 1,
                      },
                      "key": "bank_id",
                      "type": "options",
                      "label": "Bank",
                      "hidden": false,
                      "default": null,
                      "autofill": null,
                      "readonly": false,
                      "required": true,
                      "help_text": null,
                      "visible_if": {"all": [], "any": [], "not": null},
                      "constraints": [],
                      "placeholder": "Select Bank",
                      "validations": [],
                      "conditionals": [
                        {
                          "id": "019cbf74-5517-76dd-b094-ab3b3abc3e18",
                          "then": {
                            "action": "hide",
                            "targets": [
                              {"key": "account_number", "type": "field"},
                            ],
                          },
                          "when": {"field": "bank_id", "operator": "empty"},
                        },
                      ],
                      "option_properties": {
                        "data": [],
                        "type": "select",
                        "source": {
                          "when": {"all": []},
                          "method": "GET",
                          "params": [
                            {"key": "country", "value": "NG"},
                          ],
                          "enabled": true,
                          "headers": [],
                          "endpoint": "/wallets/recipients/available-banks",
                          "key_path": "*",
                          "triggers": ["init"],
                          "transport": "direct",
                          "depends_on": [],
                          "items_path": "data",
                          "value_path": "code",
                        },
                        "max_select": null,
                      },
                    },
                    {
                      "id": "019cbf73-f650-703e-8a38-49bd3ba80c9b",
                      "ui": {
                        "icon": null,
                        "mask": null,
                        "prefix": null,
                        "suffix": null,
                        "input_mode": null,
                        "max_length": null,
                        "autocomplete": null,
                        "multiline_rows": 1,
                      },
                      "key": "account_number",
                      "type": "short-text",
                      "label": "Account number",
                      "hidden": false,
                      "default": null,
                      "autofill": {
                        "map": [],
                        "when": {
                          "all": [
                            {"key": "bank_id", "operator": "not_empty"},
                            {
                              "key": "account_number",
                              "value": 10,
                              "operator": "length_gte",
                            },
                          ],
                        },
                        "method": "POST",
                        "params": [
                          {"key": "bank_id", "value": "{field: bank_id}"},
                          {
                            "key": "account_number",
                            "value": "{field: account_number}",
                          },
                          {"key": "country", "value": "NG"},
                        ],
                        "enabled": true,
                        "headers": [],
                        "trigger": "blur",
                        "endpoint": "/wallets/recipients/resolve-account-name",
                        "overwrite": "always",
                        "debounce_ms": 600,
                      },
                      "readonly": false,
                      "required": true,
                      "help_text": null,
                      "visible_if": {"all": [], "any": [], "not": null},
                      "constraints": {
                        "max": null,
                        "min": null,
                        "step": null,
                        "accept": [],
                        "max_size": null,
                        "max_length": 10,
                        "min_length": 10,
                      },
                      "placeholder": "Enter account number",
                      "validations": [],
                      "conditionals": [
                        {
                          "id": "019cbf74-cf83-74c9-bf8c-852ff87b07d7",
                          "then": {
                            "action": "show",
                            "targets": [
                              {"key": "account_name", "type": "field"},
                            ],
                          },
                          "when": {
                            "field": "account_name",
                            "operator": "not_empty",
                          },
                        },
                      ],
                    },
                    {
                      "id": "019cbf5a-a2cf-736c-9fd1-309bf369dd62",
                      "ui": {
                        "icon": null,
                        "mask": null,
                        "prefix": null,
                        "suffix": null,
                        "input_mode": null,
                        "max_length": null,
                        "autocomplete": null,
                        "multiline_rows": 1,
                      },
                      "key": "account_name",
                      "type": "short-text",
                      "label": "Account Name",
                      "hidden": false,
                      "default": null,
                      "autofill": null,
                      "readonly": true,
                      "required": false,
                      "help_text": null,
                      "visible_if": {"all": [], "any": [], "not": null},
                      "constraints": {
                        "max": null,
                        "min": null,
                        "step": null,
                        "accept": [],
                        "max_size": null,
                        "max_length": null,
                        "min_length": null,
                      },
                      "placeholder": "Account Name",
                      "validations": [],
                      "conditionals": [],
                    },
                    {
                      "id": "019cbf71-74ad-75b6-9206-bde6b437074e",
                      "ui": {
                        "icon": null,
                        "mask": null,
                        "prefix": null,
                        "suffix": null,
                        "input_mode": null,
                        "max_length": null,
                        "autocomplete": null,
                        "multiline_rows": 1,
                      },
                      "key": "email",
                      "type": "short-text",
                      "label": "Email (optional)",
                      "hidden": false,
                      "default": null,
                      "autofill": null,
                      "readonly": false,
                      "required": false,
                      "help_text": null,
                      "visible_if": {"all": [], "any": [], "not": null},
                      "constraints": {
                        "max": null,
                        "min": null,
                        "step": null,
                        "accept": [],
                        "max_size": null,
                        "max_length": null,
                        "min_length": null,
                      },
                      "placeholder": "Enter Email",
                      "validations": [],
                      "conditionals": [],
                    },
                  ],
                  "hidden": false,
                  "description": null,
                  "conditionals": [],
                },
              ],
              "textOnly": false,
              "description": null,
              "conditionals": [],
            },
          ],
          "pages_count": 1,
        },
        "meta": [],
        "name": "Nigerian Bank Transfer",
        "title": null,
        "version": 1,
        "properties": {
          "dateFormat": "YYYY-MM-DD",
          "timeFormat": "HH:mm",
          "numberFormat": {"decimal": ".", "thousand": ","},
          "datetimeFormat": "YYYY-MM-DDTHH:mm:ssZ",
        },
        "description": null,
      },
    );
  }

  urlUsaWireTransferForm() {
    navigateToFormView(formId: "019b7530-50c4-705d-873e-e7994899d7be");
  }

  globalSwiftTransferForm() {
    navigateToFormView(
      formJson: {
        "name": "Swift Transfer - Version 1",
        "description": "Collect SWIFT/BIC details for international transfers.",
        "pages": [
          {
            "id": "019b75d6-2398-769a-a279-611026c8aeeb",
            "key": "account_details",
            "label": "Account Details",
            "description": null,
            "order": 1,
            "textOnly": false,
            "hidden": false,
            "conditionals": [
              {
                "then": {
                  "action": "show",
                  "targets": [
                    {
                      "key": "business_details",
                      "type": "section",
                      "pageKey": "account_details",
                    },
                  ],
                },
                "when": {
                  "field": "recipient_type",
                  "value": "business",
                  "operator": "is",
                },
              },
            ],
            "sections": [
              {
                "id": "019b75d6-2398-769a-a279-64fd7064b65c",
                "key": "recipient_details",
                "label": "Recipient",
                "description": null,
                "order": 1,
                "hidden": false,
                "conditionals": [],
                "fields": [
                  {
                    "id": "019b75d6-2398-769a-a279-6ac912b88ed7",
                    "key": "transfer_type",
                    "label": "Transfer type",
                    "placeholder": null,
                    "help_text": null,
                    "default": "swift",
                    "type": "hidden",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": [],
                  },
                  {
                    "id": "019b75d6-2398-769a-a279-6e3a81238206",
                    "key": "recipient_country",
                    "label": "Recipient Country",
                    "placeholder": null,
                    "help_text": null,
                    "default": null,
                    "type": "country",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "code_type": "alpha_2",
                      "allow_countries": [],
                      "exclude_countries": [],
                    },
                  },
                  {
                    "id": "019b75d6-2398-769a-a279-717ff7792e2d",
                    "key": "currency",
                    "label": "Currency",
                    "placeholder": null,
                    "help_text": null,
                    "default": null,
                    "type": "options",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": [],
                    "option_properties": {
                      "type": "select",
                      "data": [
                        {"key": "USD", "value": "USD"},
                        {"key": "EUR", "value": "EUR"},
                        {"key": "GBP", "value": "GBP"},
                        {"key": "CAD", "value": "CAD"},
                      ],
                      "max_select": null,
                    },
                  },
                  {
                    "id": "019b75d6-2398-769a-a279-760c460a62c2",
                    "key": "recipient_type",
                    "label": "Paying a business?",
                    "placeholder": null,
                    "help_text": null,
                    "default": "personal",
                    "type": "options",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": [],
                    "option_properties": {
                      "type": "radio",
                      "data": [
                        {"key": "personal", "value": "Personal"},
                        {"key": "business", "value": "Business"},
                      ],
                      "max_select": null,
                    },
                  },
                  {
                    "id": "019b75d6-2398-769a-a279-791c35af2795",
                    "key": "account_holder_name",
                    "label": "Full name of the account holder",
                    "placeholder": "Enter full name",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": "name",
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75d6-2398-769a-a279-7c122460b38a",
                    "key": "recipient_email",
                    "label": "Their email (optional)",
                    "placeholder": "Enter email",
                    "help_text": null,
                    "default": null,
                    "type": "email",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": "email",
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "allowed_domains": [],
                      "disallowed_domains": [],
                      "max_length": null,
                    },
                  },
                ],
              },
              {
                "id": "019b75d6-2398-769a-a279-828bd9a4becb",
                "key": "swift_details",
                "label": "SWIFT details",
                "description": null,
                "order": 2,
                "hidden": false,
                "conditionals": [],
                "fields": [
                  {
                    "id": "019b75d6-2398-769a-a279-84ee8834c8df",
                    "key": "swift_bic",
                    "label": "SWIFT / BIC code",
                    "placeholder": "Enter SWIFT / BIC",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": "AAAAAA99AAA",
                      "input_mode": "text",
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": 11,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75d6-2398-769a-a279-8bb58c5cd105",
                    "key": "swift_account_number",
                    "label": "Account number",
                    "placeholder": "Enter account number",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75d6-2398-769a-a279-8ffb748ebfcf",
                    "key": "swift_bank_name",
                    "label": "Bank name",
                    "placeholder": "Enter bank name",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75d6-2398-769a-a279-9006f55bf1bf",
                    "key": "swift_bank_country",
                    "label": "Bank country (optional)",
                    "placeholder": null,
                    "help_text": null,
                    "default": null,
                    "type": "country",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "code_type": "alpha_2",
                      "allow_countries": [],
                      "exclude_countries": [],
                    },
                  },
                ],
              },
              {
                "id": "019b75d6-2398-769a-a279-95aaecefb13e",
                "key": "business_details",
                "label": "Business details",
                "description": null,
                "order": 3,
                "hidden": true,
                "conditionals": [],
                "fields": [
                  {
                    "id": "019b75d6-2398-769a-a279-98f8516b22e1",
                    "key": "business_name",
                    "label": "Business name",
                    "placeholder": "Enter business name",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75d6-2398-769a-a279-9d552980bbe1",
                    "key": "business_address",
                    "label": "Business address",
                    "placeholder": "Enter address",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75d6-2398-769a-a279-a1b5a59cdbf6",
                    "key": "business_city",
                    "label": "City",
                    "placeholder": "Enter city",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75d6-2398-769a-a279-a7b97e71339e",
                    "key": "business_postal_code",
                    "label": "Postal code",
                    "placeholder": "Enter postal code",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75d6-2398-769a-a279-a995bfb0e81a",
                    "key": "business_country",
                    "label": "Business country",
                    "placeholder": null,
                    "help_text": null,
                    "default": null,
                    "type": "country",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "code_type": "alpha_2",
                      "allow_countries": [],
                      "exclude_countries": [],
                    },
                  },
                ],
              },
            ],
          },
        ],
        "meta": {},
      },
    );
  }

  urlGlobalSwiftTransferForm() {
    navigateToFormView(formId: "019b7530-8b65-72cd-84c0-f2eb269690b6");
  }

  ibanSepaTransferForm() {
    navigateToFormView(
      formJson: {
        "name": "IBAN Sepa Transfer - Version 1",
        "description": "Collect IBAN details for SEPA transfers.",
        "pages": [
          {
            "id": "019b7545-c02e-7786-b747-5409f777bd8b",
            "key": "account_details",
            "label": "Account Details",
            "description": null,
            "order": 1,
            "textOnly": false,
            "hidden": false,
            "conditionals": [
              {
                "then": {
                  "action": "show",
                  "targets": [
                    {
                      "key": "business_details",
                      "type": "section",
                      "pageKey": "account_details",
                    },
                  ],
                },
                "when": {
                  "field": "recipient_type",
                  "value": "business",
                  "operator": "is",
                },
              },
            ],
            "sections": [
              {
                "id": "019b7545-c02e-7786-b747-58cfce7ae228",
                "key": "recipient_details",
                "label": "Recipient",
                "description": null,
                "order": 1,
                "hidden": false,
                "conditionals": [],
                "fields": [
                  {
                    "id": "019b7545-c02e-7786-b747-5c0e22a9d80d",
                    "key": "transfer_type",
                    "label": "Transfer type",
                    "placeholder": null,
                    "help_text": null,
                    "default": "iban",
                    "type": "hidden",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": [],
                  },
                  {
                    "id": "019b7545-c02e-7786-b747-6295be3d88f2",
                    "key": "recipient_country",
                    "label": "Recipient Country",
                    "placeholder": null,
                    "help_text": null,
                    "default": null,
                    "type": "country",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "code_type": "alpha_2",
                      "allow_countries": [],
                      "exclude_countries": [],
                    },
                  },
                  {
                    "id": "019b7545-c02e-7786-b747-67d4068a4b6f",
                    "key": "currency",
                    "label": "Currency",
                    "placeholder": null,
                    "help_text": null,
                    "default": "EUR",
                    "type": "options",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": [],
                    "option_properties": {
                      "type": "select",
                      "data": [
                        {"key": "EUR", "value": "EUR"},
                        {"key": "GBP", "value": "GBP"},
                      ],
                      "max_select": null,
                    },
                  },
                  {
                    "id": "019b7545-c02e-7786-b747-691fd661dbad",
                    "key": "recipient_type",
                    "label": "Paying a business?",
                    "placeholder": null,
                    "help_text": null,
                    "default": "personal",
                    "type": "options",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": [],
                    "option_properties": {
                      "type": "radio",
                      "data": [
                        {"key": "personal", "value": "Personal"},
                        {"key": "business", "value": "Business"},
                      ],
                      "max_select": null,
                    },
                  },
                  {
                    "id": "019b7545-c02e-7786-b747-6eebe3a8ea93",
                    "key": "account_holder_name",
                    "label": "Full name of the account holder",
                    "placeholder": "Enter full name",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": "name",
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b7545-c02e-7786-b747-707ff2288fe3",
                    "key": "recipient_email",
                    "label": "Their email (optional)",
                    "placeholder": "Enter email",
                    "help_text": null,
                    "default": null,
                    "type": "email",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": "email",
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "allowed_domains": [],
                      "disallowed_domains": [],
                      "max_length": null,
                    },
                  },
                ],
              },
              {
                "id": "019b7545-c02e-7786-b747-76450f23e1ca",
                "key": "iban_details",
                "label": "IBAN details",
                "description": null,
                "order": 2,
                "hidden": false,
                "conditionals": [],
                "fields": [
                  {
                    "id": "019b7545-c02e-7786-b747-7850d5a86381",
                    "key": "iban",
                    "label": "IBAN",
                    "placeholder": "Enter IBAN",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": "AA99 9999 9999 9999 9999 9999 9999",
                      "input_mode": "text",
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": 34,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": 34,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b7545-c02e-7786-b747-7e6533bba061",
                    "key": "iban_bic",
                    "label": "BIC / SWIFT (optional)",
                    "placeholder": "Enter BIC",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": "AAAAAA99AAA",
                      "input_mode": "text",
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": 11,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                ],
              },
              {
                "id": "019b7545-c02e-7786-b747-8014f3e6f503",
                "key": "business_details",
                "label": "Business details",
                "description": null,
                "order": 3,
                "hidden": true,
                "conditionals": [],
                "fields": [
                  {
                    "id": "019b7545-c02e-7786-b747-85184c3bdc76",
                    "key": "business_name",
                    "label": "Business name",
                    "placeholder": "Enter business name",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b7545-c02e-7786-b747-8b807505bd2d",
                    "key": "business_address",
                    "label": "Business address",
                    "placeholder": "Enter address",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b7545-c02e-7786-b747-8c6b3302fc50",
                    "key": "business_city",
                    "label": "City",
                    "placeholder": "Enter city",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b7545-c02e-7786-b747-920f2e155ef8",
                    "key": "business_postal_code",
                    "label": "Postal code",
                    "placeholder": "Enter postal code",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b7545-c02e-7786-b747-9535d57099c8",
                    "key": "business_country",
                    "label": "Business country",
                    "placeholder": null,
                    "help_text": null,
                    "default": null,
                    "type": "country",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "code_type": "alpha_2",
                      "allow_countries": [],
                      "exclude_countries": [],
                    },
                  },
                ],
              },
            ],
          },
        ],
        "meta": {},
      },
    );
  }

  urlIbanSepaTransferForm() {
    navigateToFormView(formId: "019b7530-e974-7080-83d0-9034c70c8ec2");
  }

  ukChapsTransferForm() {
    navigateToFormView(
      formJson: {
        "name": "UK (CHAPS) Transfer - Version 1",
        "description": "Collect UK CHAPS details.",
        "pages": [
          {
            "id": "019b75db-56d9-72f8-9e77-066cdcf1b91c",
            "key": "account_details",
            "label": "Account Details",
            "description": null,
            "order": 1,
            "textOnly": false,
            "hidden": false,
            "conditionals": [
              {
                "then": {
                  "action": "show",
                  "targets": [
                    {
                      "key": "business_details",
                      "type": "section",
                      "pageKey": "account_details",
                    },
                  ],
                },
                "when": {
                  "field": "recipient_type",
                  "value": "business",
                  "operator": "is",
                },
              },
            ],
            "sections": [
              {
                "id": "019b75db-56d9-72f8-9e77-0b053b2199a5",
                "key": "recipient_details",
                "label": "Recipient",
                "description": null,
                "order": 1,
                "hidden": false,
                "conditionals": [],
                "fields": [
                  {
                    "id": "019b75db-56d9-72f8-9e77-0efd92d70900",
                    "key": "transfer_type",
                    "label": "Transfer type",
                    "placeholder": null,
                    "help_text": null,
                    "default": "chaps",
                    "type": "hidden",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": [],
                  },
                  {
                    "id": "019b75db-56d9-72f8-9e77-1151d03d8d3d",
                    "key": "recipient_country",
                    "label": "Recipient Country",
                    "placeholder": null,
                    "help_text": null,
                    "default": null,
                    "type": "country",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "code_type": "alpha_2",
                      "allow_countries": ["GB"],
                      "exclude_countries": [],
                    },
                  },
                  {
                    "id": "019b75db-56d9-72f8-9e77-14f04bf85607",
                    "key": "currency",
                    "label": "Currency",
                    "placeholder": null,
                    "help_text": null,
                    "default": "GBP",
                    "type": "options",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": [],
                    "option_properties": {
                      "type": "select",
                      "data": [
                        {"key": "GBP", "value": "GBP"},
                      ],
                      "max_select": null,
                    },
                  },
                  {
                    "id": "019b75db-56d9-72f8-9e77-1bf570fb6a33",
                    "key": "recipient_type",
                    "label": "Paying a business?",
                    "placeholder": null,
                    "help_text": null,
                    "default": "personal",
                    "type": "options",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": [],
                    "option_properties": {
                      "type": "radio",
                      "data": [
                        {"key": "personal", "value": "Personal"},
                        {"key": "business", "value": "Business"},
                      ],
                      "max_select": null,
                    },
                  },
                  {
                    "id": "019b75db-56d9-72f8-9e77-1fa42633304b",
                    "key": "account_holder_name",
                    "label": "Full name of the account holder",
                    "placeholder": "Enter full name",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": "name",
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75db-56d9-72f8-9e77-23da613e86ad",
                    "key": "recipient_email",
                    "label": "Their email (optional)",
                    "placeholder": "Enter email",
                    "help_text": null,
                    "default": null,
                    "type": "email",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": "email",
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "allowed_domains": [],
                      "disallowed_domains": [],
                      "max_length": null,
                    },
                  },
                ],
              },
              {
                "id": "019b75db-56d9-72f8-9e77-26dbae9a8565",
                "key": "chaps_details",
                "label": "CHAPS details",
                "description": null,
                "order": 2,
                "hidden": false,
                "conditionals": [],
                "fields": [
                  {
                    "id": "019b75db-56d9-72f8-9e77-29d36c4318fc",
                    "key": "chaps_sort_code",
                    "label": "Sort code",
                    "placeholder": "12-34-56",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": "99-99-99",
                      "input_mode": "numeric",
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": 8,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75db-56d9-72f8-9e77-2f88335655a8",
                    "key": "chaps_account_number",
                    "label": "Account number",
                    "placeholder": "Enter account number",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": true,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": "99999999",
                      "input_mode": "numeric",
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": 8,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75db-56d9-72f8-9e77-330031ced372",
                    "key": "chaps_bank_name",
                    "label": "Bank name (optional)",
                    "placeholder": "Enter bank name",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                ],
              },
              {
                "id": "019b75db-56d9-72f8-9e77-34dd1ee546fc",
                "key": "business_details",
                "label": "Business details",
                "description": null,
                "order": 3,
                "hidden": true,
                "conditionals": [],
                "fields": [
                  {
                    "id": "019b75db-56d9-72f8-9e77-38707a78ab4a",
                    "key": "business_name",
                    "label": "Business name",
                    "placeholder": "Enter business name",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75db-56d9-72f8-9e77-3e2780974d16",
                    "key": "business_address",
                    "label": "Business address",
                    "placeholder": "Enter address",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75db-56d9-72f8-9e77-420438fbd986",
                    "key": "business_city",
                    "label": "City",
                    "placeholder": "Enter city",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75db-56d9-72f8-9e77-46c662a792ea",
                    "key": "business_postal_code",
                    "label": "Postal code",
                    "placeholder": "Enter postal code",
                    "help_text": null,
                    "default": null,
                    "type": "short-text",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "min": null,
                      "max": null,
                      "min_length": null,
                      "max_length": null,
                      "accept": [],
                      "max_size": null,
                      "step": null,
                    },
                  },
                  {
                    "id": "019b75db-56d9-72f8-9e77-49b6ddbce747",
                    "key": "business_country",
                    "label": "Business country",
                    "placeholder": null,
                    "help_text": null,
                    "default": null,
                    "type": "country",
                    "hidden": false,
                    "visible_if": {"all": [], "any": [], "not": null},
                    "conditionals": [],
                    "readonly": false,
                    "required": false,
                    "ui": {
                      "icon": null,
                      "prefix": null,
                      "suffix": null,
                      "mask": null,
                      "input_mode": null,
                      "autocomplete": null,
                      "multiline_rows": 1,
                      "max_length": null,
                    },
                    "autofill": null,
                    "validations": [
                      {
                        "rule": "required_if",
                        "params": ["{field:recipient_type}", "business"],
                      },
                    ],
                    "constraints": {
                      "code_type": "alpha_2",
                      "allow_countries": [],
                      "exclude_countries": [],
                    },
                  },
                ],
              },
            ],
          },
        ],
        "meta": {},
      },
    );
  }

  urlUkChapsTransferForm() {
    navigateToFormView(formId: "019b7531-3c6c-71a3-84d6-296b62f3004f");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16),
          child: SafeArea(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: <Widget>[
                const SizedBox(height: 36),
                Center(
                  child: Text(
                    "USA Wire Transfer Form",
                    style: Theme.of(context).textTheme.bodyLarge,
                  ),
                ),
                const SizedBox(height: 16),
                ElevatedButton(
                  onPressed: usaWireTransferForm,
                  child: const Text('JSON Form'),
                ),
                const SizedBox(height: 12),
                ElevatedButton(
                  onPressed: urlUsaWireTransferForm,
                  child: const Text('URL Form by ID'),
                ),
                const SizedBox(height: 36),
                Center(
                  child: Text(
                    "Global Swift Transfer",
                    style: Theme.of(context).textTheme.bodyLarge,
                  ),
                ),
                const SizedBox(height: 16),
                ElevatedButton(
                  onPressed: globalSwiftTransferForm,
                  child: const Text('JSON Form'),
                ),
                const SizedBox(height: 12),
                ElevatedButton(
                  onPressed: urlGlobalSwiftTransferForm,
                  child: const Text('URL Form by ID'),
                ),
                const SizedBox(height: 36),
                Center(
                  child: Text(
                    "IBAN Sepa Transfer",
                    style: Theme.of(context).textTheme.bodyLarge,
                  ),
                ),
                const SizedBox(height: 16),
                ElevatedButton(
                  onPressed: ibanSepaTransferForm,
                  child: const Text('JSON Form'),
                ),
                const SizedBox(height: 12),
                ElevatedButton(
                  onPressed: urlIbanSepaTransferForm,
                  child: const Text('URL Form by ID'),
                ),
                const SizedBox(height: 36),
                Center(
                  child: Text(
                    "UK Chaps Transfer",
                    style: Theme.of(context).textTheme.bodyLarge,
                  ),
                ),

                const SizedBox(height: 16),
                ElevatedButton(
                  onPressed: ukChapsTransferForm,
                  child: const Text('JSON Form'),
                ),
                const SizedBox(height: 12),
                ElevatedButton(
                  onPressed: urlUkChapsTransferForm,
                  child: const Text('URL Form by ID'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
